server:
  port: 8090
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active:
      - "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Microservice"
    version: "1.0"
logging:
  level:
    com:
      eazybytes:
        loans: DEBUG
